version: '3' 
services: 
  CrossroadsServiceCrmSync: 
    build: 
      context: ../../ 
      dockerfile: ./deployment/docker/prod.Dockerfile
    container_name: crds-service-crm-sync
    image: crdschurch/crds-service-crm-sync:${DOCKER_TAG:-local} 
    # env_file:
    #   - ../../.env
    ports:
      - "5000:80"